kind: PersistentVolume
apiVersion: v1
metadata:
  name: kube-cheerp-volume
  labels:
    type: local
spec:
  storageClassName: cheerp-storage
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt2/NAS/kube/cheerpweb/data/

